import {parseRoute,routeLength,bufferedBounds,areaKm2,mapQuery,validateMap,nearestDistance,project} from './core.mjs';
import * as store from './storage.mjs';
import {TrailMap} from './map.mjs';
import {setupAdventure} from './adventure.mjs';
import {setupActivity} from './activity.mjs';
import {setupExplore} from './explore.mjs';
const $=id=>document.getElementById(id),BASE=new URL('./',import.meta.url),jobs=new Map(),messages=new Map();let routes=[],metas=new Map(),selected=null,selectedMap=null,currentView='routes',shellReady=false,reg=null,toastTimer,watch=null,fix=null,follow=true,storeOK=false,selectSerial=0;
const map=new TrailMap($('map'),()=>{follow=false;$('follow').classList.remove('selected');});
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function button(label,cls,fn){const b=node('button',cls,label);b.onclick=fn;return b;}
function formatSize(n){return n>=1048576?(n/1048576).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB';}
function toast(t){clearTimeout(toastTimer);$('toast').textContent=t;$('toast').classList.remove('hide');toastTimer=setTimeout(()=>$('toast').classList.add('hide'),6000);}
function failure(e){return e?.name==='QuotaExceededError'?'裝置空間不足，未能儲存。請刪除唔需要嘅離線底圖。':e?.message||'操作未能完成，請重試。';}
function setBanner(t){$('banner').textContent=t;$('banner').classList.toggle('hide',!t);}
function network(){$('network').textContent=navigator.onLine?'● 目前在線':'○ 目前離線';if(currentView==='map')mapBadge();}
function nav(name){if(adventure.isEditing()&&name!=='map'){toast('請先儲存或取消自訂路線編輯。');return;}currentView=name;for(const n of ['routes','map','offline','help'])$(n+'View').classList.toggle('hide',n!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='map'){requestAnimationFrame(()=>{map.resize();mapBadge();});}if(name==='offline')storageInfo();explore.viewChanged();window.scrollTo({top:0});}
function mini(route){const box=node('div','mini'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 340 145');svg.setAttribute('aria-hidden','true');const ps=route.segments.map(s=>s.map(project));let minx=Infinity,miny=Infinity,maxx=-Infinity,maxy=-Infinity;for(const p of ps.flat()){minx=Math.min(minx,p[0]);maxx=Math.max(maxx,p[0]);miny=Math.min(miny,p[1]);maxy=Math.max(maxy,p[1]);}const scale=Math.min(275/Math.max(1,maxx-minx),108/Math.max(1,maxy-miny)),cx=(minx+maxx)/2,cy=(miny+maxy)/2;for(const s of ps){const d=s.map((p,i)=>(i?'L':'M')+(170+(p[0]-cx)*scale).toFixed(2)+','+(72+(p[1]-cy)*scale).toFixed(2)).join(' ');for(const [color,w] of [['white',7],['#4e875d',3.5]]){const path=document.createElementNS('http://www.w3.org/2000/svg','path');for(const[k,v]of Object.entries({d,fill:'none',stroke:color,'stroke-width':w,'stroke-linecap':'round','stroke-linejoin':'round'}))path.setAttribute(k,v);svg.append(path);}}box.append(svg,node('span','chip',route.count.toLocaleString()+' 點'));return box;}
function renderRoutes(){$('routeList').replaceChildren();$('empty').classList.toggle('hide',routes.length>0);for(const r of routes){const card=node('article','route-card');card.append(mini(r));const body=node('div','route-body');body.append(node('h2','',r.name));const facts=node('div','facts');facts.append(node('b','',(r.length/1000).toFixed(2)),document.createTextNode(' km 軌跡 · '+r.segments.length+' 段'));body.append(facts);const meta=node('div','route-meta'),m=metas.get(r.id);meta.append(node('span','status-pill'+(m?'':' pending'),m?'↓ 底圖已下載':'只有路線 · 未下載底圖'));if(m)meta.append(node('small','muted',formatSize(m.size)));body.append(meta);const actions=node('div','card-actions');actions.append(button('開啟地圖','primary',()=>selectRoute(r.id)),button('離線設定','',()=>{nav('offline');document.getElementById('dl-'+r.id)?.scrollIntoView({block:'center'});}));const del=button('×','small',()=>deleteRoute(r));del.setAttribute('aria-label','刪除 '+r.name);del.disabled=jobs.has(r.id);actions.append(del);body.append(actions);card.append(body);$('routeList').append(card);}}
function renderDownloads(){$('downloadList').replaceChildren();$('downloadEmpty').classList.toggle('hide',routes.length>0);for(const r of routes){const card=node('article','download-card');card.id='dl-'+r.id;card.append(node('h2','',r.name));const m=metas.get(r.id);card.append(node('p','muted',m?'已儲存 '+formatSize(m.size)+' · '+new Date(m.downloaded).toLocaleDateString()+' · 周邊 '+(m.buffer/1000)+' km · '+(m.detailLevel||'舊版基本地形；重載可加入建築物'):'GPX／KML 已儲存，底圖尚未下載。'));const row=node('div','row'),label=node('label','','周邊範圍 '),select=node('select');select.setAttribute('aria-label',r.name+' 下載範圍');for(const [v,t]of [[500,'500 m'],[1000,'1 km'],[2000,'2 km']]){const o=node('option','',t);o.value=v;o.selected=(r.buffer||1000)===v;select.append(o);}select.disabled=jobs.has(r.id);select.onchange=async()=>{const old=r.buffer;r.buffer=Number(select.value);try{await store.put('routes',r);renderDownloads();}catch(e){r.buffer=old;select.value=old;toast(failure(e));}};label.append(select);row.append(label);if(jobs.has(r.id))row.append(button('取消下載','',()=>jobs.get(r.id)?.abort()));else row.append(button(m?'重新下載':'下載底圖','primary',()=>download(r)));if(m){const del=button('刪除底圖','',()=>deleteMap(r));del.disabled=jobs.has(r.id);row.append(del);}card.append(row);const status=node('div','dlstatus');status.id='status-'+r.id;const area=areaKm2(bufferedBounds(r.segments,r.buffer||1000));status.textContent=messages.get(r.id)||(m?((shellReady?'✓ 路線及底圖可離線使用':'底圖已儲存；App 離線安裝仍需確認')+(m.buffer!==(r.buffer||1000)?'。新選擇範圍尚未下載。':'')):'預計涵蓋 '+area.toFixed(1)+' km²；30 km² 或以下包括建築物及地標。');if(status.textContent.startsWith('下載失敗'))status.classList.add('error');card.append(status);$('downloadList').append(card);}}
async function refresh(){routes=(await store.getAll('routes')).sort((a,b)=>b.created-a.created);metas=new Map((await store.listMapMeta()).map(m=>[m.id,m]));renderRoutes();renderDownloads();storageInfo();await explore.refresh();}
function mapBadge(){$('mapTitle').textContent=selected?.name||'瀏覽地圖';$('mapMeta').textContent=selected?(selected.length/1000).toFixed(2)+' km 檔案軌跡 · '+selected.count+' 點':'毋須路線 · 自由瀏覽及框選離線地區';$('mapBadge').classList.toggle('hide',!selected);$('mapBadge').textContent=selected?'實線：目前路線 · 路線底圖'+(metas.has(selected.id)?'已下載':'未下載'):' ';for(const b of document.querySelectorAll('[data-route-required]'))b.disabled=!selected;$('mapOptions').disabled=!selected;}
async function selectRoute(id){const serial=++selectSerial;try{const r=await store.get('routes',id);if(!r)return;const b=await store.get('maps',id);if(serial!==selectSerial)return;selected=r;selectedMap=b||null;adventure.routeChanged();nav('map');requestAnimationFrame(()=>{map.resize();map.setRoute(r,b);mapBadge();gpsStatus();});}catch(e){toast(failure(e));}}
async function importFiles(files){if(!storeOK){toast('本機儲存未就緒，請先處理頁面頂部提示。');return;}let success=0,errors=[];for(const f of files){try{if(f.size>25*1024*1024)throw Error('檔案超過 25 MB。');if(!/\.(gpx|kml)$/i.test(f.name))throw Error('請使用 GPX 或 KML。');const r=parseRoute(await f.text(),f.name);if(/^Devils-Nose-Hike-updated-2018\.(gpx|kml)$/i.test(f.name))r.note='已知原始網頁列出 4.4 km 來回，但此檔案軌跡約 2.95 km，兩者不一致。請確認實際起點及回程。';await store.put('routes',r);success++;}catch(e){errors.push(f.name+'：'+failure(e));}}await refresh();nav('routes');toast('已匯入 '+success+' 條路線。'+(errors.length?' '+errors.join('；'):''));}
async function demo(){$('demo').disabled=true;try{if(!storeOK)throw Error('本機儲存未就緒。');const a=await fetch(new URL('assets/devils-route.json',BASE)),b=await fetch(new URL('assets/devils-base.json',BASE));if(!a.ok||!b.ok)throw Error('未能載入示範資料，請先連線開啟一次。');const original=await a.json(),data=validateMap(await b.json()),id='demo-devils-nose',route={...original,id,created:Date.now(),length:routeLength(original.segments),count:original.segments.flat().length,buffer:1000,sourceName:'Walking SA uploaded GPX / KML',note:'Walking SA 網頁列出 4.4 km 來回，但提供嘅 GPX／KML 軌跡約 2.95 km，兩者不一致。The Knob Lookout 是離開此軌跡嘅原檔標記。'};const basemap={id,data,bounds:{west:138.803,south:-34.705,east:138.843,north:-34.661},buffer:1000,downloaded:new Date('2026-09-03T00:00:00Z').getTime(),size:new Blob([JSON.stringify(data)]).size};await store.importDemo(route,basemap);await refresh();await selectRoute(id);toast('示範路線及離線底圖已儲存。');}catch(e){toast(failure(e));}finally{$('demo').disabled=false;}}
function setDownloadStatus(id,t){messages.set(id,t);const n=$('status-'+id);if(n)n.textContent=t;}
async function readResponse(response,id,signal){if(!response.ok)throw Error('地圖服務回應 '+response.status+'。');const limit=32*1024*1024;if(Number(response.headers.get('content-length'))>limit)throw Error('地圖大於 64 MB，請縮小範圍。');if(!response.body)return response.json();const reader=response.body.getReader(),decoder=new TextDecoder();let length=0,parts=[],last=0;while(true){if(signal.aborted){await reader.cancel();throw Error('已取消下載。');}const {done,value}=await reader.read();if(done)break;length+=value.byteLength;if(length>limit){await reader.cancel();throw Error('地圖大於 64 MB，請縮小範圍。');}parts.push(decoder.decode(value,{stream:true}));if(length-last>131072){last=length;setDownloadStatus(id,'正在下載 '+formatSize(length)+'…');}}parts.push(decoder.decode());return JSON.parse(parts.join(''));}
async function download(route){if(jobs.size){toast('請等目前下載完成，或先取消。');return;}if(!navigator.onLine){toast('目前離線。請連線後下載底圖。');return;}let bounds,query;try{bounds=bufferedBounds(route.segments,route.buffer||1000);query=mapQuery(bounds);}catch(e){toast(failure(e));return;}const controller=new AbortController();jobs.set(route.id,controller);setDownloadStatus(route.id,'正在取得周邊地圖…');renderDownloads();renderRoutes();const timer=setTimeout(()=>controller.abort('timeout'),150000);let data,lastError;try{for(const endpoint of ['https://overpass.kumi.systems/api/interpreter','https://overpass-api.de/api/interpreter']){try{const response=await fetch(endpoint,{method:'POST',body:new URLSearchParams({data:query}),signal:controller.signal,credentials:'omit'});data=validateMap(await readResponse(response,route.id,controller.signal));break;}catch(e){lastError=e;if(controller.signal.aborted)throw e;setDownloadStatus(route.id,'第一個地圖服務暫時未能完成，正在嘗試另一個服務…');}}if(!data)throw lastError||Error('未能取得地圖。');if(controller.signal.aborted)throw Error('已取消下載。');setDownloadStatus(route.id,'下載完成，正在寫入裝置…');const record={id:route.id,bounds,buffer:route.buffer||1000,data,detailLevel:areaKm2(bounds)<=30?'建築物及地標':'基本地形',downloaded:Date.now(),size:new Blob([JSON.stringify(data)]).size};await store.put('maps',record);messages.delete(route.id);if(selected?.id===route.id){selectedMap=record;map.setBase(record);}toast('「'+route.name+'」底圖已儲存。舊底圖要重新下載先會加入建築物。');}catch(e){const cancelled=controller.signal.aborted&&controller.signal.reason!=='timeout';messages.set(route.id,cancelled?'已取消下載。既有底圖（如有）仍然保留。':'下載失敗：'+(controller.signal.reason==='timeout'?'服務逾時，請稍後重試。':failure(e))+(metas.has(route.id)?' 既有底圖仍然保留。':''));}finally{clearTimeout(timer);jobs.delete(route.id);await refresh();mapBadge();}}
function ask(title,text){return new Promise(resolve=>{$('confirmTitle').textContent=title;$('confirmText').textContent=text;const d=$('confirm');let done=false;const finish=v=>{if(done)return;done=true;d.close();d.oncancel=null;resolve(v);};$('cancelConfirm').onclick=()=>finish(false);$('acceptConfirm').onclick=()=>finish(true);d.oncancel=e=>{e.preventDefault();finish(false);};d.showModal();});}
async function deleteRoute(r){if(jobs.has(r.id)){toast('請先取消下載。');return;}if(!await ask('刪除呢條路線？','「'+r.name+'」及其離線底圖會從呢部裝置刪除。原始 GPX／KML 檔案不受影響。'))return;try{await store.removeRoute(r.id);if(selected?.id===r.id){selected=null;selectedMap=null;map.setRoute(null,null);if(currentView==='map')nav('routes');}await refresh();toast('路線已刪除。');}catch(e){toast(failure(e));}}
async function deleteMap(r){if(jobs.has(r.id))return;if(!await ask('刪除離線底圖？','保留「'+r.name+'」嘅路線。下次需要連線重新下載底圖。'))return;try{await store.removeMap(r.id);messages.delete(r.id);if(selected?.id===r.id){selectedMap=null;map.setBase(null);}await refresh();mapBadge();toast('底圖已刪除，路線已保留。');}catch(e){toast(failure(e));}}
function details(){if(!selected)return;const r=selected,c=$('detailsContent');$('detailsTitle').textContent=r.name;c.replaceChildren();const label=node('label','','路線名稱'),input=node('input');input.value=r.name;input.maxLength=160;input.setAttribute('aria-label','路線名稱');c.append(label,input,button('儲存名稱','',async()=>{const name=input.value.trim();if(!name){toast('請輸入路線名稱。');return;}try{const latest=await store.get('routes',r.id);if(!latest)throw Error('路線已被刪除。');await store.put('routes',{...latest,name});selected={...latest,name};await refresh();mapBadge();$('detailsTitle').textContent=name;toast('名稱已儲存。');}catch(e){toast(failure(e));}}));c.append(node('p','muted',(r.length/1000).toFixed(2)+' km 檔案軌跡，未必等於完整來回行程。'));if(r.note)c.append(node('p','notice',r.note));c.append(node('h3','','路線標記'));if(!r.waypoints.length)c.append(node('p','muted','呢個檔案冇獨立標記。'));r.waypoints.forEach((w,i)=>c.append(button((i+1)+'. '+w.name+' · '+w.point[1].toFixed(5)+', '+w.point[0].toFixed(5),'waypoint',()=>{$('details').close();follow=false;map.focus(w.point);})));c.append(node('p','fineprint','來源檔案：'+r.sourceName));$('details').showModal();}
function gpsStatus(){if(!fix)return;const age=Math.max(0,Math.round((Date.now()-fix.timestamp)/1000));$('gpsStatus').textContent=age>20?'舊位置：'+age+' 秒前，未能確認目前位置。':`精度 ±${Math.round(fix.coords.accuracy)} m`+(selected?' · 距軌跡約 '+Math.round(nearestDistance([fix.coords.longitude,fix.coords.latitude],selected.segments))+' m':'');map.setFix(fix,follow&&age<=20);adventure.onFix(fix);}
function stopGPS(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;fix=null;map.setFix(null);adventure.onFix(null);$('gps').textContent='◎ 開始定位';$('follow').classList.remove('selected');}
function gps(){if(activity.isRecording()&&watch!==null){toast('請先暫停或完成活動。');return;}if(watch!==null){stopGPS();$('gpsStatus').textContent='定位已停止。';return;}if(!isSecureContext||location.protocol==='file:'){$('gpsStatus').textContent='請用 HTTPS 已部署網址開啟，再授權 GPS 定位。';return;}if(!navigator.geolocation){$('gpsStatus').textContent='此瀏覽器唔支援 GPS 定位。';return;}follow=true;$('follow').classList.add('selected');$('gps').textContent='■ 停止定位';$('gpsStatus').textContent='等候定位授權及 GPS 訊號…';watch=navigator.geolocation.watchPosition(p=>{fix=p;gpsStatus();activity.onFix(p);},e=>{activity.onError();if(e.code===1){stopGPS();$('gpsStatus').textContent='未獲定位授權，請到瀏覽器設定允許定位。';}else $('gpsStatus').textContent='暫時未能更新 GPS 位置，請到空曠位置再試。';},{enableHighAccuracy:true,maximumAge:0,timeout:20000});}
async function storageInfo(){if(!navigator.storage?.estimate)return;try{const s=await navigator.storage.estimate();$('storageInfo').textContent='此網站約佔 '+formatSize(s.usage||0)+(s.quota?'／配額 '+formatSize(s.quota):'');}catch{}}
function requestShellStatus(worker){return new Promise(resolve=>{if(!worker){resolve(false);return;}const ch=new MessageChannel(),t=setTimeout(()=>resolve(false),5000);ch.port1.onmessage=e=>{clearTimeout(t);ch.port1.close();resolve(Boolean(e.data?.ready));};worker.postMessage({type:'STATUS'},[ch.port2]);});}
async function setupOffline(){if(!('serviceWorker'in navigator)||!isSecureContext||location.protocol==='file:'){$('shellStatus').textContent='需要 HTTPS 網址先可安裝離線 App';setBanner('此版本需部署到 HTTPS 網址。直接開啟下載檔案，未能完成 PWA 安裝。');return;}try{reg=await navigator.serviceWorker.register(new URL('sw.js',BASE),{scope:BASE.pathname});if(reg.waiting)$('updates').classList.remove('hide');reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)$('updates').classList.remove('hide');});});const ready=await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('離線安裝未完成，請保持連線再重開。')),20000))]);shellReady=await requestShellStatus(ready.active);$('shellStatus').textContent=shellReady?'App 可離線開啟':'App 離線資源未完整，請連線重開';$('shellIcon').textContent=shellReady?'✓':'○';renderDownloads();if(!shellReady)setBanner('App 離線安裝尚未完成，請保持連線再重開。');}catch(e){$('shellStatus').textContent='App 離線安裝未完成';setBanner(failure(e));}}
for(const b of document.querySelectorAll('nav button'))b.onclick=()=>nav(b.dataset.view);$('import').onclick=$('firstImport').onclick=()=>$('files').click();$('files').onchange=async e=>{const files=[...e.target.files];e.target.value='';await importFiles(files);};$('demo').onclick=demo;$('back').onclick=()=>nav('routes');$('zoomIn').onclick=()=>map.zoom(.7);$('zoomOut').onclick=()=>map.zoom(1.4);$('fit').onclick=()=>{follow=false;$('follow').classList.remove('selected');map.fit();};$('follow').onclick=()=>{if(!fix){toast('先開始 GPS 定位。');return;}follow=true;$('follow').classList.add('selected');gpsStatus();};$('gps').onclick=gps;$('mapOptions').onclick=details;$('closeDetails').onclick=()=>$('details').close();$('persist').onclick=async()=>{try{if(!navigator.storage?.persist){toast('此瀏覽器未提供持續儲存功能，出發前請檢查離線地圖。');return;}const ok=await navigator.storage.persist();toast(ok?'已取得持續儲存資格；仍請保留原始路線檔。':'瀏覽器未批出持續儲存資格，現有資料仍可使用。');}catch(e){toast(failure(e));}};$('update').onclick=()=>{if(!reg?.waiting){toast('未有待更新版本。');return;}navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});reg.waiting.postMessage({type:'UPDATE'});};window.addEventListener('online',network);window.addEventListener('offline',network);document.addEventListener('visibilitychange',()=>{if(!document.hidden)gpsStatus();});setInterval(()=>{if(fix)gpsStatus();},10000);window.addEventListener('pagehide',()=>{if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;});window.addEventListener('pageshow',e=>{if(e.persisted){stopGPS();$('gpsStatus').textContent='請重新開始定位。';}});
const adventure=setupAdventure({map,getRoute:()=>selected,isReady:()=>storeOK,replaceRoute:r=>{if(selected?.id===r.id)selected=r;},refresh,selectRoute,toast,failure,pauseFollow:()=>{follow=false;$('follow').classList.remove('selected');},showMap:()=>nav('map'),showRoutes:()=>nav('routes')});
const activity=setupActivity({map,getRoute:()=>selected,isReady:()=>storeOK,isEditing:()=>adventure.isEditing(),ensureGPS:()=>{if(watch===null)gps();},stopGPS,toast,failure});
const explore=setupExplore({map,nav,getView:()=>currentView,isReady:()=>storeOK,isEditing:()=>adventure.isEditing(),pauseFollow:()=>{follow=false;$('follow').classList.remove('selected');},jobs,ask,toast,failure,formatSize,storageInfo});
async function boot(){network();try{await store.openStore();storeOK=true;await refresh();await adventure.init();await explore.init();await activity.init();}catch(e){setBanner('本機儲存無法使用：'+failure(e)+' 請離開私密瀏覽或檢查裝置空間。');$('import').disabled=$('firstImport').disabled=$('demo').disabled=true;}nav('map');await setupOffline();}boot();
