import {project,unproject,joinWays} from './core.mjs';
export class TrailMap{
 constructor(canvas,onPan){this.c=canvas;this.ctx=canvas.getContext('2d');this.route=null;this.base=null;this.shapes=[];this.center=project([138.82,-34.682]);this.units=5;this.fix=null;this.pointers=new Map();this.gesture=null;this.onPan=onPan;new ResizeObserver(()=>this.resize()).observe(canvas);const state=()=>{const p=[...this.pointers.values()];return p.length>1?{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2,d:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}:p.length?{...p[0],d:0}:null;};canvas.addEventListener('pointerdown',e=>{this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);this.gesture=state();});canvas.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const next=state(),last=this.gesture;if(last){this.onPan?.();this.center[0]-=(next.x-last.x)*this.units;this.center[1]-=(next.y-last.y)*this.units;if(next.d&&last.d){const r=canvas.getBoundingClientRect();this.zoom(last.d/next.d,next.x-r.left,next.y-r.top);}else this.draw();}this.gesture=next;});for(const kind of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(kind,e=>{this.pointers.delete(e.pointerId);this.gesture=state();});canvas.addEventListener('wheel',e=>{e.preventDefault();this.onPan?.();const r=canvas.getBoundingClientRect();this.zoom(Math.exp(Math.sign(e.deltaY)*.16),e.clientX-r.left,e.clientY-r.top);},{passive:false});this.resize();}
 resize(){const r=this.c.getBoundingClientRect();if(!r.width||!r.height)return;this.w=r.width;this.h=r.height;const d=Math.min(3,devicePixelRatio||1);this.c.width=this.w*d;this.c.height=this.h*d;this.ctx.setTransform(d,0,0,d,0,0);this.draw();}
 screen(p){return [(p[0]-this.center[0])/this.units+this.w/2,(p[1]-this.center[1])/this.units+this.h/2];}
 zoom(f,x=this.w/2,y=this.h/2){const u=Math.max(.15,Math.min(30000,this.units*f));this.center[0]+=(x-this.w/2)*(this.units-u);this.center[1]+=(y-this.h/2)*(this.units-u);this.units=u;this.draw();}
 setRoute(route,base,fit=true){this.route=route;this.projected=route?.segments.map(s=>s.map(project))||[];this.setBase(base);if(fit)this.fit();else this.draw();}
 setBase(base){this.base=base;this.shapes=[];for(const e of base?.data.elements||[]){let raw=[];if(e.geometry)raw=[e.geometry];else if(e.members)raw=e.members.filter(m=>m.type==='way'&&m.geometry).map(m=>m.geometry);let paths=raw.filter(p=>p.length>1&&p.every(x=>x&&Number.isFinite(x.lon)&&Number.isFinite(x.lat))).map(p=>p.map(x=>[x.lon,x.lat]));if(e.members)paths=joinWays(paths);if(!paths.length)continue;this.shapes.push({tags:e.tags||{},paths:paths.map(p=>p.map(project))});}this.draw();}
 fit(){if(!this.route)return;const pts=[...this.projected.flat(),...this.route.waypoints.map(w=>project(w.point))];let minx=Infinity,miny=Infinity,maxx=-Infinity,maxy=-Infinity;for(const p of pts){minx=Math.min(minx,p[0]);maxx=Math.max(maxx,p[0]);miny=Math.min(miny,p[1]);maxy=Math.max(maxy,p[1]);}this.center=[(minx+maxx)/2,(miny+maxy)/2];this.units=Math.max((maxx-minx)/Math.max(100,this.w-120),(maxy-miny)/Math.max(100,this.h-180),.8)*1.1;this.draw();}
 focus(point){this.center=project(point);this.units=Math.min(2,this.units);this.draw();}
 setFix(fix,follow=false){this.fix=fix;if(follow&&fix)this.center=project([fix.coords.longitude,fix.coords.latitude]);this.draw();}
 line(points,color,width,dash=[]){const ctx=this.ctx;ctx.beginPath();points.forEach((p,i)=>{const [x,y]=this.screen(p);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
 draw(){const c=this.ctx;if(!c||!this.w)return;c.clearRect(0,0,this.w,this.h);c.fillStyle='#f0f0e8';c.fillRect(0,0,this.w,this.h);c.lineCap='round';c.lineJoin='round';const b=this.base?.bounds;if(b){const a=this.screen(project([b.west,b.north])),z=this.screen(project([b.east,b.south]));c.save();c.beginPath();c.rect(a[0],a[1],z[0]-a[0],z[1]-a[1]);c.clip();c.fillStyle='#e8eddf';c.fillRect(0,0,this.w,this.h);for(const s of this.shapes){const t=s.tags,water=t.natural==='water'||t.waterway==='riverbank',forest=t.natural==='wood'||t.landuse==='forest';if(water||forest){c.beginPath();for(const p of s.paths){p.forEach((v,i)=>{const [x,y]=this.screen(v);if(i)c.lineTo(x,y);else c.moveTo(x,y);});if(p.length>2)c.closePath();}c.fillStyle=water?'#b0d3d1':'#d4e1c7';c.fill('evenodd');}}
 for(const s of this.shapes){const t=s.tags;if(t.waterway&&t.waterway!=='riverbank')for(const p of s.paths)this.line(p,'#9cbdc1',1.3);}
 const labels=new Set();for(const s of this.shapes){const t=s.tags;if(!t.highway)continue;const trail=['path','footway','track','steps','bridleway','cycleway'].includes(t.highway);for(const p of s.paths){if(!trail)this.line(p,'#bec4b4',5);this.line(p,trail?'#a2ab97':'#fffef5',trail?1.5:3,trail?[4,4]:[]);if(t.name&&!labels.has(t.name)&&this.units<6){const v=this.screen(p[Math.floor(p.length/2)]);if(v[0]>40&&v[0]<this.w-100&&v[1]>75&&v[1]<this.h-60){labels.add(t.name);c.font='10px sans-serif';c.textAlign='center';c.lineWidth=3;c.strokeStyle='#f6f8f0';c.strokeText(t.name,v[0],v[1]);c.fillStyle='#657365';c.fillText(t.name,v[0],v[1]);}}}}c.restore();c.strokeStyle='#b6c2ad';c.lineWidth=1;c.setLineDash([5,5]);c.strokeRect(a[0],a[1],z[0]-a[0],z[1]-a[1]);c.setLineDash([]);}
 for(const s of this.projected||[]){this.line(s,'#fcfff9',8);this.line(s,'#288561',4.5);}if(this.route){const markers=[{point:this.route.segments[0][0],label:'S'},...this.route.waypoints.map((w,i)=>({point:w.point,label:String(i+1)}))];for(const m of markers){const [x,y]=this.screen(project(m.point));c.beginPath();c.arc(x,y,10,0,Math.PI*2);c.fillStyle='#fcfff8';c.fill();c.strokeStyle='#265640';c.lineWidth=2;c.stroke();c.fillStyle='#265640';c.font='bold 10px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(m.label,x,y);}}
 if(this.fix){const f=this.fix,pt=[f.coords.longitude,f.coords.latitude],p=this.screen(project(pt)),stale=Date.now()-f.timestamp>20000,color=stale?'#8a8a83':'#258bdb',acc=f.coords.accuracy/Math.max(.01,Math.cos(pt[1]*Math.PI/180))/this.units;c.beginPath();c.arc(p[0],p[1],Math.min(10000,acc),0,Math.PI*2);c.fillStyle=stale?'#88888822':'#258bdb22';c.fill();c.beginPath();c.arc(p[0],p[1],7,0,Math.PI*2);c.fillStyle=color;c.fill();c.strokeStyle='white';c.lineWidth=3;c.stroke();}
 const lat=unproject(this.center)[1],mpp=this.units*Math.cos(lat*Math.PI/180),target=85*mpp,pow=10**Math.floor(Math.log10(target)),len=[1,2,5,10].map(x=>x*pow).filter(x=>x<=target).pop()||pow;c.fillStyle='#fffffff0';c.fillRect(14,this.h-53,110,39);c.font='10px sans-serif';c.textAlign='left';c.textBaseline='alphabetic';c.fillStyle='#294b3b';c.fillText(len>=1000?(len/1000)+' km':len+' m',24,this.h-35);c.beginPath();c.moveTo(24,this.h-27);c.lineTo(24,this.h-23);c.lineTo(24+len/mpp,this.h-23);c.lineTo(24+len/mpp,this.h-27);c.strokeStyle='#294b3b';c.lineWidth=1.5;c.stroke();}
}
